# -*- coding: utf-8 -*-
"""1_triaje.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qpXVauMrGTX-cTKAJamvZpIHN3P4ZbYZ
"""

from transformers import AutoTokenizer, AutoModelForMaskedLM

# Use a pipeline as a high-level helper
from transformers import pipeline

mDeBERTa = pipeline("zero-shot-classification", model="MoritzLaurer/mDeBERTa-v3-base-mnli-xnli")

mensajes_pacientes = [
    "Tengo un dolor muy fuerte en el pecho y se me duerme el brazo izquierdo.",
    "Hola, necesito saber si el doctor Martínez atiende los jueves.",
    "Se me acabó la pastilla de la presión, necesito la receta para comprarla.",
    "Mi hijo tiene fiebre de 38 desde ayer y llora mucho, pero come bien.",
    "Quiero cancelar mi cita de mañana, no podré asistir.",
    "Necesito que me renueven el enalapril que se me terminó ayer",
    "Siento una presión muy fuerte en el pecho y me falta el aire",
    "Quisiera saber los horarios de atención para la próxima semana"
]

patient_messages = [
    "I have very severe chest pain and my left arm feels numb.",
    "Hello, I need to know if Dr. Martínez sees patients on Thursdays.",
    "I ran out of my blood pressure pills; I need the prescription to buy them.",
    "My child has had a 38°C fever since yesterday and cries a lot, but is eating well.",
    "I want to cancel my appointment for tomorrow; I won't be able to attend.",
    "I need my enalapril renewed; I ran out yesterday.",
    "I feel very strong pressure in my chest and I'm short of breath.",
    "I would like to know the office hours for next week."
]

mensajes_pacientes[1]

etiquetas_triaje = [
    "Urgencia Vital (Roja)",
    "Consulta Administrativa",
    "Renovación de Receta",
    "Consulta Médica No Urgente"
]

triage_labels = [
    "Life-Threatening Emergency (Red)",
    "Administrative Inquiry",
    "Prescription Renewal",
    "Non-Urgent Medical Consultation"
]

output = mDeBERTa(mensajes_pacientes[0], etiquetas_triaje)

output_en= mDeBERTa(patient_messages[0], triage_labels)





print(output)
print(output_en)

print("bryan darwin luna bravo--")